FROM python:%%PYTHON_VERSION%% AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV UV_PROJECT_ENVIRONMENT=/opt/venv

RUN mkdir -p src/responsaas && \
    touch src/responsaas/__init__.py && \
    touch README.md

COPY ./uv.lock ./pyproject.toml ./
RUN uv sync --frozen --no-dev --extra server

FROM python:%%PYTHON_VERSION%% AS runner
ENV PYTHONUNBUFFERED=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

COPY --from=builder /opt/venv /opt/venv
COPY ./ ./

ENTRYPOINT ["responsaas"]
CMD ["--host=0.0.0.0", "--port=7564"]
